version: "3"
services:
  # SQL Database
  postgres:
    image: "postgres:14.1"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog_development
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # # Key-value NoSQL Database
  # redis:
  #   image: "redis:4.0"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis:/data
  #   command: redis-server --requirepass foobared

  # # S3 compatible object storage
  # minio:
  #   # minio does not follow good versioning,
  #   # so we don't lock a certain version but use latest.
  #   image: minio/minio:RELEASE.2020-10-03T02-19-42Z
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     MINIO_ACCESS_KEY: MINIOACCESSKEY
  #     MINIO_SECRET_KEY: M!N!0S3CR3T000
  #   command: server /minio-data
  #   volumes:
  #     - ./data/minio:/minio-data

  # Mailcatcher runs a simple smtp server to catch and display any emails sent to it
  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:0.7.1
    ports:
    - "1080:1080"
    - "1025:1025"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
  #   ports:
  #     - "9200:9200"
  #   environment:
  #     - "discovery.type=single-node"
  #     - "cluster.name=elasticsearch-rails"
  #     - "cluster.routing.allocation.disk.threshold_enabled=false"

